
export const   POST_REQUEST_FORM = "POST_REQUEST_FORM";
export const   POST_SUCCESS_FORM = "POST_SUCCESS_FORM";
export const   POST_FAILURE_FORM = "POST_FAILURE_FORM";


export const GET_REQUEST_FORM = "GET_REQUEST_FORM";
export const GET_SUCCESS_FORM = "GET_SUCCESS_FORM";
export const GET_FAILURE_FORM = "GET_FAILURE_FORM";